slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan_reliable
    mode: mapping # localization

    # map_file_name: '.../surround_view_segbev/configs/slam_toolbox/maps/main_wbt/main_wbt'
    # map_start_pose: [0.0, 5.75, -1.57]
    # map_start_at_dock: true

    map_update_interval: 3.0
