SIMULATION_TIME_STEP = 32
USED_CAMERA_MODEL_FOLDER_NAME = 'ZED_2'

EGO_VEHICLE_MAX_SPEED = 3.0  # Км/ч
EGO_VEHICLE_MAX_STEERING_ANGLE = 35.0  # Градусы

CONTROL_MODE = 'Auto'  # 'Manual'

USED_DETECTOR_FOLDER_NAME = 'YOLO11'
USED_SEGMENTOR_FOLDER_NAME = 'FastSegBEV'  # 'FastSeg'
