global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: base_link
      robot_base_frame: base_link
      rolling_window: True
      width: 160       # Метры
      height: 200      #
      resolution: 0.05 # 1 пиксель = 0.05 метров (1 метр = 20 пикселей)
      robot_radius: 0.5
      plugins: ['obstacle_layer', 'inflation_layer']
      obstacle_layer:
        plugin: 'nav2_costmap_2d::ObstacleLayer'
        observation_sources: costmap
        costmap:
          topic: /scan
          data_type: LaserScan
      inflation_layer:
        plugin: 'nav2_costmap_2d::InflationLayer'
        inflation_radius: 0.7

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: base_link
      robot_base_frame: base_link
      rolling_window: True
      width: 160
      height: 200
      resolution: 0.05
      robot_radius: 0.5
      plugins: ['obstacle_layer', 'inflation_layer']
      obstacle_layer:
        plugin: 'nav2_costmap_2d::ObstacleLayer'
        observation_sources: costmap
        costmap:
          topic: /scan
          data_type: LaserScan
      inflation_layer:
        plugin: 'nav2_costmap_2d::InflationLayer'
        inflation_radius: 0.7

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ['FollowPath']
    FollowPath:
      plugin: 'dwb_core::DWBLocalPlanner'
      critics: [
        'RotateToGoal', 
        'Oscillation', 
        'BaseObstacle', 
        'GoalAlign', 
        'PathAlign', 
        'PathDist', 
        'GoalDist', 
      ]
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      BaseObstacle.scale: 0.02
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0