local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      width: 20.0        # Meters
      height: 25.0       #
      resolution: 1.0    #
      robot_radius: 3.64 #
      plugins: ['static_layer', 'inflation_layer']
      static_layer:
        plugin: 'nav2_costmap_2d::StaticLayer'
        map_subscribe_transient_local: True
        topic: /local_costmap
        subscribe_to_updates: True # Обновлять локальную карту стоимости в реальном времени
      inflation_layer:
        plugin: 'nav2_costmap_2d::InflationLayer'
        inflation_radius: 1.5

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.0
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ['progress_checker']
    goal_checker_plugins: ['general_goal_checker']
    controller_plugins: ['FollowPath']
    use_realtime_priority: false
    progress_checker:
      plugin: 'nav2_controller::SimpleProgressChecker'
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: True
      plugin: 'nav2_controller::SimpleGoalChecker'
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: 'dwb_core::DWBLocalPlanner'
      min_vel_x: 0.0  # M/s
      max_vel_x: 2.75 # * 3.6 = Km/h
      acc_lim_x: 2.5
      acc_lim_theta: 3.0