pointcloud_to_laserscan:
  ros__parameters:
    min_height: 0.0
    max_height: 0.75
    angle_min: -1.57
    angle_max: 1.57
    angle_increment: 0.00153
    queue_size: 100
    scan_time: 0.01
    range_min: 0.75
    range_max: 100.0
    target_frame: 'base_link'
    transform_tolerance: 0.01
    use_inf: true